### ISSUE TITLE
Maybe one final backport to 1.12.2 when released?

### ISSUE THREAD

**Issue by XxDuckyUxX** [Andromander/Gaia-Dimension#111]
Every time I play on 1.16.5, I crash even with 11GBs allocated. So I have given up and just stayed on 1.12.2. This mod is amazing, but I would love to play with the newer features without crashing like crazy. 

I know 1.12.2 is outdated, but there is still a wide community on this version, so I think it would be cool :D

**Comment by Andromander** [comment]
Unfortunately, that is a huge ask that I simply cannot do alone.

1.12 is years old, and I've since moved all my mods from that version and have forgotten most of how that version worked due to all the internal changes. On top of that, a lot of logic is just simply harder to translate backwards, whether it's because it makes use of new systems or is just generally better (ie. Slabs, Entities, Structures). In some cases, it might even be impossible,

On top of this, I work alone. I just don't have the time or energy to maintain multiple versions, even if it is for just one update. Other people are welcome to create a port that I can then release, but because Curseforge is a bit not smart in the head, any release will mean saying the mod is on older versions, negating the newer ones. Once I have ported, I am extremely unlikely to got back a version to fix it.
