### ISSUE TITLE
Cannot get gaia cobblestone.  (Feel free to close this issue.)

### ISSUE THREAD

**Issue by ArmageddonX430** [Andromander/Gaia-Dimension#112]
- Minecraft: 1.12.2
 - Forge: 14.23.5.2885
 - Gaia Dimension: 1.12.2-1.0.5

Steps to reproduce the behavior. This is required for easier diagnosis:
1. Gaia stone in front.
2. Vanilla unenchanted iron pickaxe in hand.
3. Mine and get gaia stone and not gaia cobblestone.

Additional context:
I feel bad even reporting this issue as it's from a version of the mod/minecraft that's probably no longer being maintained.  And even worse than that, it's in a modpack of my own design that is just packed with every weird mod I wanted to explore in 1.12.2 before I said goodbye to that minecraft version for good.  I see other issues referring to stuff later in the mod so its almost guaranteed to be an issue of the version I'm playing, or a mod interaction with God knows how many mods.

I can list the mods in my modpack but I doubt they would be of any use.  Let me know if you want that modlist.  And like I said in the title: 100% feel no guilt about closing this issue, I just wanted to report it in case it would be of use.

**Comment by Andromander** [comment]
Yeah, it's an error with a block drop where it drops itself rather than the cobble version.
It is possible to still obtain Gaia Cobblestone through mixing different fluids (I forget the exact combination), but indeed, 1.12 is a long gone version that is no longer maintained. Definitely fixed in later versions.
