### ISSUE TITLE
BlockColors crash if another mod has an error

### ISSUE THREAD

**Issue by WenXin20** [Andromander/Gaia-Dimension#59]
`Minecraft v1.14.4`
`Forge v28.1.109`
`Gaia Dimension v1.1.0`

- If another mod has an error, such as with an invalid config file, Gaia Dimension will crash instead of displaying the forge error screen and what went wrong with the other mod/config. 
- This could mislead the player into thinking Gaia Dimension is at fault instead of something else.
- [Crash Report](https://gist.github.com/WenXin20/736035eba5ef27098a6294324ff36bd1)

**Comment by Andromander** [comment]
Thank you for the report.

Unfortunately, this kind of issue cannot be resolved on this end as it is caused inside of software I cannot touch (in this case, it might be Forge). I can't recall how to resolve it - I have seen this occur with another mod of mine, but caused by a different mod error - but best I can suggest is finding the culprit mod and reporting the issue to them. I will, however, keep this issue pinned for anyone else that may come across this.

As for anyone who has come across this issue, the error is not caused by Gaia Dimension. Best I can guess is that, due to the way Forge loads Events, errors that happen may not actually be in the right place. I would say report this to Forge, but quite frankly, I don't know if that's the cause of the crash, or if they can fix it.
What I can tell you is how to find the culprit mod. You can use a technique known as "Binary Searching", which involves removing half the mods you have and testing. If one of those halves errors, half that again and keep testing. It may take a while depending on the size of your mod list, but it is always faster than removing one mod at a time.
If this error does persist with Gaia Dimension on its own or is removed (there needs to be another mod that uses block tinting), feel free to leave a comment below.

I'll be keeping this issue open and pinned for reference if anyone does find the crash.

**Comment by WenXin20** [comment]
I have also reported this same type of crash to another mod at Rexbas/Teletubbies-Mod#8, which was able to be resolved. I believe some null checks were added. The crash also can happen if a config file is changed incorrectly.

**Comment by WenXin20** [comment]
Does that help any with this crash?

**Comment by Andromander** [comment]
I've got some information about this kind of crash. There is some involvement with loading, specifically multi-threaded loading, as well as not being able to stop loading before the crash would happen. I'll be looking into some solutions, since I can't tell exactly what is null (I'd assume it would be the blocks/items), and there seems to be more than one way to handle tinted blocks.

**Comment by WenXin20** [comment]
Alright, thanks for looking into this!

**Comment by Andromander** [comment]
https://github.com/Andromander/Gaia-Dimension/releases/tag/untagged-2ef5a8a0ce31cc02fd7f I've made small changes into how tinting is done. This contains a pre-Alpha build with the change implemented. I assume the issue is fixed, but I'll leave it open until confirmed.

**Comment by WenXin20** [comment]
Thanks! I'll try testing it out later today.

**Comment by WenXin20** [comment]
Its working, thanks!
