### ISSUE TITLE
npe in 1.15.2-1.2.1

### ISSUE THREAD

**Issue by kreezxil** [Andromander/Gaia-Dimension#65]
using forge build 31.2.4

https://paste.ee/p/ep5fH

**Comment by Andromander** [comment]
Hmm, I've seen this issue before once, but it happened when I put an unreleased beta of a mod in, and then it magically stopped when I bumped Forge version in my dev environment. It didn't do this beforehand, either.

Do you have any steps to reproduce?

**Comment by Andromander** [comment]
Checked current environment. Unable to reproduce this error on loading the mod or reloading resources. Could be a conflict with another mod.

**Comment by kreezxil** [comment]
did you try it with forge build 31.2.4? I'm being told that it is caused by
the class name renaming they did in 31.2.0, and yes, 31.2.4, got some more
renames.

**Comment by Andromander** [comment]
It wouldn't be that, otherwise the crash would be ClassNotFoundException or MethodNotFoundException. The issue at hand is a null RegistryObject, however, at the point in time the object is being called, it shouldn't be null (registration is before client setup). It isn't the first time client events are culprits when another error is the cause. 

Asking around, the only way this could happen is if another error happened before registration, shutting down EventBus. Is there a latest.log including this crash?

**Comment by kreezxil** [comment]
you're right, you can close this ticket. I just started an instance with
only your mod and the issue didn't happen.

**Comment by Andromander** [comment]
No problem. If you need any assistance finding the issue, you can refer back to this ticket with a client log. Troubleshooting crashes post-1.13 Forge is a little weird now for some reason.
