### ISSUE TITLE
Gaia dimension using to much ram

### ISSUE THREAD

**Issue by snooglexX** [Andromander/Gaia-Dimension#77]
It seems like the Gaia dimension is causing a memory leak? The over world is fine but the moment I go into the dimension my ram climbs constantly without stopping and considering I only allowed Minecraft to use 5gb but it passed that with no end I am also running it on a server my client crashed out at 12gb and someone else crashed at 22gb ram used

**Comment by Andromander** [comment]
Unfortunately, I am going to need a *lot* more information than this because as far as I'm concerned, it isn't happening to me, and there's no info to go off of. 
This issue also does not conform to the provided Bug Report template which asks for versions.

**Comment by snooglexX** [comment]
I don't really know how to explain it I'm using this mod with Valhelsia 3 and had no ram issues until i installed the Gaia mod pack to it ever since adding Gaia dimensions the ram has been increasing uncontrollably  unless Gaia dimensions require 10-20+GB ram?

**Comment by Andromander** [comment]
Details I'm missing (crucial) are Forge, Minecraft, and Gaia Versions that were in the bug template. Additional details I do need, however, are more extensive. Things like what run arguments are used, CPU, possibly a profile of the game's performance (that is if it can track down memory usage. As far as I know, there's nothing that should be consuming RAM whatsoever; it's technically a stripped-down overworld with basic features, mobs, and biome generation.

**Comment by Andromander** [comment]
Upon investigation, the memory leaks appear to be occurring in Native Memory, aka. Off-Heap Memory. This means that, even if a profile could have been made by anyone, the information required wouldn't exist. Running the mod on a server doesn't cause issues with the server itself, but users experience this issue as the underlying cause is in rendering.
I'll remove the `non-compliant` label as supplying info won't help.
