### ISSUE TITLE
[1.16.4] Crash in Gaiadimension with TwerkItMeal installed

### ISSUE THREAD

**Issue by remplerus** [Andromander/Gaia-Dimension#78]
**Versions ("Latest" is NOT a version):**
 - Minecraft: 1.16.4
 - Forge: 35.1.13
 - TwerkItMeal: 1.3.4
 - Gaia Dimension: 1.3.0

**Crash Report**
https://gist.github.com/remplerus/194e74f21420a619838b97e5d774ec19

**To Reproduce:**
Steps to reproduce the behaviour. This is required for easier diagnosis:
1. Install Gaia Dimension and TwerkItMeal Mods
2. Crouch like you want to grow anything
3. Crash

**Additional context**
This just happens if TwerkItMeal Mods is installed.
Workaround: Add gaiadimension to blacklist in TwerkItMeal config.

**Comment by remplerus** [comment]
also made a issue on TwerkItMeal: https://github.com/KyleBCox/TwerkItMeal/issues/4

**Comment by ticticboooom** [comment]
for record this looks like an issue on my end, will keep this updated if that changes. but imma look at it now

**Comment by Andromander** [comment]
@KyleBCox it'll have to be because of the logic in place here. It's a simple fix on my end: implement IGrowable onto my Crystal Growth blocks. Alternatively, as the Crystal Growth do not have additional growth stages like Grass, I'll have to revise the logic. Also not difficult, but I can sort it out over here.

I'm surprised the crash wasn't showing up earlier because it should be breaking without other mods, looking at what I have here.

**Comment by Andromander** [comment]
[This release](https://github.com/Andromander/Gaia-Dimension/releases/tag/untagged-338c1c26e062bf4aa372) should contain a fix to the crash. I removed a bit of code that wouldn't have worked and was possibly the cause of the crash here.
