### ISSUE TITLE
Implement Biome-Dependant Mobs

### ISSUE THREAD

**Issue by Andromander** [Andromander/Gaia-Dimension#9]
Tracking Issue
To better represent ecological diversity, each biome in Gaia will host at least 1 unique mob for each Biome. Unique mobs exclude Bosses, if said biome will have a boss. Perhaps biomes that will not have a boss should have 2 unique mobs, though this is yet to be decided. For now, 1 unique mob for each biome.

Pink Agate Forest: Agate Golem
Blue Agate Taiga: Howlite Wolf
Green Agate Jungle: Lush Lizard, Markuzar Plant
Purple Agate Swamp: Spellbound Elemental, Muckling
Crystal Plains: Crystal Golem
Fossil Woodland: Rocky Luggeroth, Rugged Lurmorus
Volcaniclands: Spitfire
Mineral River: ???
Mineral Reservoir: ???
Goldstonelands: ???
Static Wasteland: Slingbolt
Mutant Agate Wildwood: Growth Extractor

Along with this, the Goldstonelands will have special Goldstone mobs due to this plague. Also, the Mineral Rivers will share a unique mob with the Mineral Reservoir. As for the Fossil Woodland, it is likely that a whole set of new mobs will be created for that biome, pushing the general mobs' spawn rate lower.

**Comment by ZombieEnderman5** [comment]
Perhaps the Volcaniclands mob should be based around fire, lava, or something of the sort?

**Comment by ZombieEnderman5** [comment]
Did you mean `Dependent` (issue title)? Or maybe it's spelled `Dependant` in some parts of the world, but the spell-checker's underlining that in red.

**Comment by OceanusProcellarum** [comment]
Wow I haven't been active for a while. Issue is that I don't have my own computer and the computer I was borrowing was out of commission for a while. I was actually in the middle of making textures for the items lacking textures. Sorry about that. Anyways, I was wondering for Goldstonelands, would you consider formless mobs? Larger mobs could be large piles of goldstone dust (look like sludge monsters) or even something more mystical, like floating gold shards. Smaller ones could be variations of those or even little specks of goldstone plague that hurt you like silverfish. Mostly I'm only capable of producing ideas but if I can get back on the computer I can design models and such. Since goldstone is a plague, perhaps the goldstone mobs are hostile to all other mobs and infect the others? Like a zombie and a villager

**Comment by OceanusProcellarum** [comment]
For the mineral river, I could imagine semi-transparent crystalline entities that match the water's color, so it looks like they're an extension of the water, but also in the form of a crystal

**Comment by Andromander** [comment]
I think I've implemented enough mobs for now. Until later releases, this will do.
